name: suji
version: 1.0.0+1
publish_to: none
description: Suka Ngaji is Application for all moslem to read quran and set up Adzan alarm.
environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: ">=3.27.3"

dependencies:
  cupertino_icons: ^1.0.8
  android_alarm_manager_plus: ^3.0.2
  flutter_local_notifications: ^18.0.1
  audioplayers: ^5.1.0
  connectivity_plus: ^4.0.2
  dartz: 0.10.1
  equatable: 2.0.5
  flutter_screenutil: 5.9.0
  freezed_annotation: ^2.4.1
  get: 4.7.2
  geolocator: ^10.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  share_plus: ^7.1.0
  shimmer: 3.0.0
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0
  rxdart: ^0.27.7
  hive: ^2.2.3
  logger: ^2.0.1
  auto_size_text: ^3.0.0
  sklite: ^1.0.0
  lottie: ^2.6.0
  

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mockito: ^5.4.2

dependency_overrides:
  analyzer: ^6.0.0
  archive: ^4.0.2
  win32: ^5.10.1

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/animation/
    - assets/model/daily_pray.json
    - assets/model/asmaul_husna.json
    - assets/model/model.json
  uses-material-design: true
